/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bcet.gym.management.system;


import com.email.durgesh.Email;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import  java.sql.*;

/**
 *
 * @author deves
 */
public class Delete extends javax.swing.JFrame {
    Connection con;
    Statement stm;
    ResultSet rs;
    String Email;
    
    int g;
    
     public void connect()
    {
        try
        {
           
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bcet gym project","root","");
           stm=con.createStatement();
        }
        catch(Exception ex)
                {
                  JOptionPane.showMessageDialog(this,ex.getMessage());  
                }
    }
      public void send_mail() //Function to send a email
    {
        try
        {
          Email email=new Email("codefreaksdevelopers@gmail.com","Codefreaks14581"); 
          //setting the sender adress
          email.setFrom("codefreaksdevelopers@gmail.com","CODEFREAKS");
          //Setting subject
          email.setSubject("BCET Gym");
          //Now setting the Content
          email.setContent("<h1> Your Record has been removed from BCET Gym Sucessfullly.Contact the management if it was not you who initialized it,else ignore.  Thanking you,Codefreaks. </h1>","text/html");
          //Now adding the recievers adress
          email.addRecipient(Email);
          //Now sending the email
          
          email.send();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        } 
      }
    /**
     * Creates new form Delete
     */
    public Delete() {
        initComponents();
        connect();
        this.setResizable(false);
        this.setSize(1000,800);
    }
int id;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        jLabel1.setText("Enter the  gym Card Number");
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 380, 40);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jInternalFrame1.getContentPane().add(jTextField1);
        jTextField1.setBounds(400, 10, 110, 40);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Contact", "Fee Paid Upto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jInternalFrame1.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 80, 750, 260);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Search");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton2);
        jButton2.setBounds(630, 10, 170, 50);

        jLabel3.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 204));
        jInternalFrame1.getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 160, 810, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Clear");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton4);
        jButton4.setBounds(620, 360, 180, 50);

        jTextField2.setText("jTextField2");
        jInternalFrame1.getContentPane().add(jTextField2);
        jTextField2.setBounds(80, 380, 420, 22);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(60, 110, 850, 470);

        jLabel2.setFont(new java.awt.Font("Algerian", 2, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Remove record");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 10, 390, 64);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bcet/gym/management/system/images/back.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 80, 80);

        jButton3.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 153));
        jButton3.setText("DELETE RECORD");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(100, 600, 740, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(this,"Are you sure you want to go back?","Exit",JOptionPane.YES_NO_OPTION);
        
        if(a==JOptionPane.YES_OPTION)
            this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       id=Integer.parseInt(jTextField1.getText());
        
        
        try
        {
            String sql="select Member_Name,Age,Email,Fee from gymdaata where Gym_Card_no="+id+" ";
        rs=stm.executeQuery(sql);
        
        DefaultTableModel model=( DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        
        while(rs.next())
        {
              Email=rs.getString("Email");
            model.addRow(new Object[] {rs.getString("Member_Name"),rs.getString("Age"),rs.getString("Email"),rs.getString("Fee")});
            jLabel3.setText("Confirm the details of Gym card Number "+id+" Found in the record.");
          
        }
        
        }
        catch(Exception y)
        {
            JOptionPane.showMessageDialog(this,y.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       int x= JOptionPane.showConfirmDialog(this,"Are You Sure To Delete The Record","Confirm!!",JOptionPane.YES_NO_OPTION);
        if(x==JOptionPane.YES_OPTION)
        {
      try{
        String sql="delete from gymdaata where  Gym_Card_No="+id;
        stm.executeUpdate(sql);
        JOptionPane.showMessageDialog(this,"Record Deleted Sucessfully!!");
      }
      catch(Exception y){
          JOptionPane.showMessageDialog(this,y.getMessage());
      }
        }
        send_mail();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextField1.setText("");
        jLabel3.setText("");
        
        try
        {
          
        DefaultTableModel model=( DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        
        while(rs.next())
        {
            model.addRow(new Object[] {rs.getString(""),rs.getString(""),rs.getString(""),rs.getString(""),rs.getString("")});
           
        
        }
        }
        catch(Exception z)
                {
                JOptionPane.showMessageDialog(this,z.getMessage());
                }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
