/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bcet.gym.management.system;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import  java.sql.*;

/**
 *
 * @author deves
 */
public class Fee extends javax.swing.JFrame {
     Connection con;
    Statement stm;
    ResultSet rs;
   
     public void connect()
    {
        try
        {
           
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bcet gym project","root","");
           stm=con.createStatement();
        }
        catch(Exception ex)
                {
                  JOptionPane.showMessageDialog(this,ex.getMessage());  
                }
    };
    /**
     * Creates new form Fee
     */
    public Fee() {
        initComponents();
        connect();
        this.setResizable(false);
        this.setSize(1000,800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UPDATE = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("THE FEE FORUM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 10, 360, 64);

        UPDATE.setBackground(new java.awt.Color(204, 255, 204));
        UPDATE.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Deatils", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        UPDATE.setLayout(null);

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setText("Enter the Gym card number");
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 9, 320, 40);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jTextField1);
        jTextField1.setBounds(390, 12, 180, 40);

        UPDATE.add(jInternalFrame1);
        jInternalFrame1.setBounds(60, 30, 610, 90);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jToggleButton1.setText("Search");
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        UPDATE.add(jToggleButton1);
        jToggleButton1.setBounds(250, 130, 210, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UPDATE.add(jLabel3);
        jLabel3.setBounds(10, 190, 360, 40);

        jTextField2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        UPDATE.add(jTextField2);
        jTextField2.setBounds(380, 190, 280, 40);

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton2.setText("UPDATE");
        jToggleButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton2.setEnabled(false);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        UPDATE.add(jToggleButton2);
        jToggleButton2.setBounds(260, 260, 210, 50);

        getContentPane().add(UPDATE);
        UPDATE.setBounds(160, 180, 700, 380);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bcet/gym/management/system/images/back.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 20, 80, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int a=JOptionPane.showConfirmDialog(this,"Are you sure to go back?","Exit!!",JOptionPane.YES_NO_OPTION);
         if(a==JOptionPane.YES_OPTION)
         {
             this.dispose();
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
      
        int g=Integer.parseInt(jTextField1.getText());
         String sql="select Fee from gymdaata where Gym_Card_no="+g+" ";
         
         if(jToggleButton1.isSelected())
         {
        try{
       
        rs=stm.executeQuery(sql);
        while(rs.next())
        {
        String fee=rs.getString("Fee");
         jTextField2.setText(fee);
        }
        jLabel3.setText("Fee Paid Upto");
        jToggleButton1.setText("Clear");
        jToggleButton2.setEnabled(true);
       
       
        }
        catch(Exception y)
        {
            JOptionPane.showMessageDialog(this, y.getMessage());
        }
         }
         else
         {
             jLabel3.setText("");
             jTextField2.setText("");
             jTextField1.setText("");
             jToggleButton1.setText("Search");
             jToggleButton2.setEnabled(false);
              jToggleButton2.setText("UPDATE");
         }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        if(jToggleButton2.isSelected())
        {
             jLabel3.setText("Enter the fee paid upto");
                jTextField2.setText("");
                jToggleButton2.setText("Done");
                
        }
        else
        {
             int g=Integer.parseInt(jTextField1.getText());
           String sql="update gymdaata  set Fee='"+jTextField2.getText()+"' ";
           try
           {
             stm.executeUpdate(sql);
             JOptionPane.showMessageDialog(this,"Record Updated Sucessfully!!");
           }
           catch(Exception y)
           {
               JOptionPane.showMessageDialog(this,y.getMessage());
           }
               
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UPDATE;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
