/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bcet.gym.management.system;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import  java.sql.*;
/**
 *
 * @author deves
 */
public class Search extends javax.swing.JFrame {

     Connection con;
    Statement stm;
    ResultSet rs;
   
     public void connect()
    {
        try
        {
           
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bcet gym project","root","");
           stm=con.createStatement();
        }
        catch(Exception ex)
                {
                  JOptionPane.showMessageDialog(this,ex.getMessage());  
                }
    };
    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
        connect();
        this.setResizable(false);
        this.setSize(1200,800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 30, 1040, 70);

        jTable1.setBackground(new java.awt.Color(204, 255, 255));
        jTable1.setFont(new java.awt.Font("Arial Black", 2, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Contact", "Profession", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 110, 950, 170);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bcet/gym/management/system/images/back.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 20, 80, 80);

        jInternalFrame1.setBackground(new java.awt.Color(204, 204, 255));
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        jLabel2.setText("Enter the gym card number to search");
        jInternalFrame1.getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 370, 26);
        jInternalFrame1.getContentPane().add(jTextField1);
        jTextField1.setBounds(390, 70, 180, 30);

        jButton2.setFont(new java.awt.Font("Algerian", 2, 24)); // NOI18N
        jButton2.setText("Clear");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton2);
        jButton2.setBounds(30, 120, 240, 80);

        jButton3.setFont(new java.awt.Font("Algerian", 2, 24)); // NOI18N
        jButton3.setText("Search");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton3);
        jButton3.setBounds(340, 120, 230, 80);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(230, 340, 620, 260);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 290, 750, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(this,"Are you Sure to go back?","Exit!!",JOptionPane.YES_NO_OPTION);
        if(a==JOptionPane.YES_OPTION)
        {
           this.dispose();  
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jLabel3.setText("");
        jLabel1.setText("");
        try
        {
          
        DefaultTableModel model=( DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        
        while(rs.next())
        {
            model.addRow(new Object[] {rs.getString(""),rs.getString(""),rs.getString(""),rs.getString(""),rs.getString("")});
           
        
        }
        }
        catch(Exception z)
                {
                JOptionPane.showMessageDialog(this,z.getMessage());
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int id=Integer.parseInt(jTextField1.getText());
        
        
        try
        {
            String sql="select Member_Name,Age,Contact,Profression,Gender from gymdaata where Gym_Card_no="+id+" ";
        rs=stm.executeQuery(sql);
        DefaultTableModel model=( DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        
        while(rs.next())
        {
            model.addRow(new Object[] {rs.getString("Member_Name"),rs.getString("Age"),rs.getString("Contact"),rs.getString("Profression"),rs.getString("Gender")});
            jLabel1.setText("Following are the details of Gym card Number "+id);
            jLabel3.setText("Go to database for detailed Record of Gym card Number "+id);
        }
        
        }
        catch(Exception y)
        {
            JOptionPane.showMessageDialog(this,y.getMessage());
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
