/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bcet.gym.management.system;

import com.email.durgesh.Email;
import javax.swing.JOptionPane;
import java.sql.*;


/**
 *
 * @author deves
 */
public class Six extends javax.swing.JFrame {

    Connection con;
    Statement stm;
    ResultSet result;
     String Email=null;
    
    public void connect()
    {
        try
        {
           
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bcet gym project","root","");
           stm=con.createStatement();
        }
        catch(Exception ex)
                {
                  JOptionPane.showMessageDialog(this,ex.getMessage());  
                }
    };
    public void send_mail() //Function to send a email
    {
        try
        {
          Email email=new Email("codefreaksdevelopers@gmail.com","Codefreaks14581"); 
          //setting the sender adress
          email.setFrom("codefreaksdevelopers@gmail.com","CODEFREAKS");
          //Setting subject
          email.setSubject("BCET Gym");
          //Now setting the Content
          email.setContent("<h1> Thankyou very much for joining the BCET Gym.Your Gym Card number and your date of Bitrh are your User ID And Paasword for memeber login for the app.  Thanking you,Codefreaks. </h1>","text/html");
          //Now adding the recievers adress
          email.addRecipient(Email);
          //Now sending the email
          
          email.send();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        } 
    }
   
            
    /**
     * Creates new form Six
     */
    public Six() {
        initComponents();
        connect();
        this.setResizable(false);
        this.setSize(1250,800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField10 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Algerian", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Member's Form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 20, 290, 60);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 200, 21);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setText("Age");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 80, 200, 21);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setText("Father's Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 120, 200, 21);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setText("Mothers's Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 160, 200, 21);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setText("Weight(in kgs)");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 200, 200, 21);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jRadioButton1.setText("Male");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(220, 250, 70, 29);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 250, 200, 21);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jRadioButton2.setText("Female");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(320, 250, 89, 29);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jRadioButton3.setText("Others");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(440, 250, 90, 29);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setText("Nationality");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 310, 200, 21);

        jComboBox1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "Indian", "NRI" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(210, 310, 260, 27);

        jTextField1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(210, 30, 360, 30);

        jTextField2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(210, 70, 360, 30);

        jTextField3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(210, 110, 360, 30);

        jTextField4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(210, 150, 360, 30);

        jTextField5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(210, 190, 360, 27);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 110, 590, 370);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Other Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setText("Contact Number");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 20, 137, 40);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel10.setText("E-mail");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 50, 54, 40);

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel11.setText("Profession");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 90, 90, 40);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel12.setText("Address");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 140, 69, 40);

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel13.setText("City");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 190, 35, 40);

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel14.setText("State");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 230, 45, 40);

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel15.setText("Fee Paid Upto(Month)");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(10, 280, 182, 40);

        jTextField7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel2.add(jTextField7);
        jTextField7.setBounds(270, 60, 300, 30);

        jComboBox2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "Student", "Self-Employeed", "Gov-Employee" }));
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(270, 100, 230, 27);

        jTextField8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel2.add(jTextField8);
        jTextField8.setBounds(270, 140, 300, 30);

        jTextField9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel2.add(jTextField9);
        jTextField9.setBounds(270, 190, 300, 30);

        jComboBox3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chattisgarh", "Goa", "Gujrat", "Haryana", "Himachal Pradesh", "Jammu and Kashmir", "Jharkhand", "Karnatka", "Kerela", "Madhya Pradesh", "Maharastra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odhisa", "Punjab", "Rajsthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal", " ", " " }));
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(270, 240, 230, 27);

        jTextField10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel2.add(jTextField10);
        jTextField10.setBounds(270, 280, 300, 30);

        jTextField6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel2.add(jTextField6);
        jTextField6.setBounds(270, 22, 300, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(630, 110, 590, 370);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bcet/gym/management/system/images/back.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 10, 80, 80);

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jButton2.setText("SAVE");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1030, 500, 180, 50);

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel16.setText("Allot Gym Card Number");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(90, 500, 340, 35);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(440, 490, 90, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String Name=null;
        String FN=null;
        String MN=null;
        String Weight=null;
        String Gender=null;
        String Nation=null;
        String Contact=null;
       
        String Prof=null;
        String Add=null;
        String City=null;
        String State=null;
        String Fee=null; 
        int GymN,age;
       
         {
              Name= jTextField1.getText();
              age=Integer.parseInt(jTextField2.getText());
              FN=jTextField3.getText();
              MN=jTextField4.getText();
              Weight=jTextField5.getText();
              
              
              if(jRadioButton1.isSelected())
              {
                  Gender="Male";
              }
              if(jRadioButton2.isSelected())
              {
                  Gender="Female";
              }
              if(jRadioButton3.isSelected())
              {
                  Gender="Others";
              }
              
              
             int c=jComboBox1.getSelectedIndex();
             if(c==1)
             {
                 Nation="Indian";
             }
             if(c==2)
             {
                 Nation="NRI";
             }
             
            Contact=jTextField6.getText();
            Email=jTextField7.getText();
            
            int d=jComboBox2.getSelectedIndex();
            if(d==1)
            {
                Prof="Student";
            }
             if(d==2)
            {
                Prof="Self-Empoyeed";
            }
              if(d==3)
            {
                Prof="Government-Employee";
            }
                    
            Add=jTextField8.getText();
            City=jTextField9.getText();
            
            int x=jComboBox3.getSelectedIndex();
            
            if(x==1)
            {
                State="Andhra Pradesh";
            }
            if(x==2)
            {
                State="Arunachal Pradesh";
            }
            if(x==3)
            {
                State="Assam";
            }
            if(x==4)
            {
                State="Bihar";
            }
            if(x==5)
            {
                State="Chhattisgarh";
            }
             if(x==6)
            {
                State="Goa";
            }
            if(x==7)
            {
                State="Gujarat";
            }
            if(x==8)
            {
                State="Haryana";
            }
            if(x==9)
            {
                State="Himachal Pradesh";
            }
            if(x==10)
            {
                State="Jammu and Kashmir";
            }
            if(x==11)
            {
                State="Jharkhand";
            }
            if(x==12)
            {
                State="Karnataka";
            }
            if(x==13)
            {
                State="Kerala";
            }
            if(x==14)
            {
                State="Madhya Pradesh";
            }
            if(x==15)
            {
                State="Maharashtra";
            }
             if(x==16)
            {
                State="Manipur";
            }
             if(x==17)
            {
                State="Meghalaya";
            }
            if(x==18)
            {
                State="Mizoram";
            }
            if(x==19)
            {
                State="Nagaland";
            }
            if(x==20)
            {
                State="Odhisa";
            }
            if(x==21)
            {
                State="Punjab";
            }
            if(x==22)
            {
                State="Rajsthan";
            }
            if(x==23)
            {
                State="Sikkim";
            }
            if(x==24)
            {
                State="Tamil Nadu";
            }
            if(x==25)
            {
                State="Telangana";
            }
            if(x==26)
            {
                State="Tripura";
            }
            if(x==27)
            {
                State="Uttar Pradesh";
            }
             if(x==28)
            {
                State="Uttrakhnd";
            }
              if(x==29)
            {
                State="West Bengal";
            }
         }
         
         Fee=jTextField10.getText();
         
         String str="";
         if(jTextField11.getText().equals(str))
         {
             JOptionPane.showMessageDialog(this,"Gym card Allotment is Compulsory!!","ERROR!!",JOptionPane.OK_OPTION);
         }
         else
         {
              GymN=Integer.parseInt(jTextField11.getText());
               
               try
               {
                   String sql="insert into gymdaata values("+GymN+",'"+Name+"',"+age+",'"+FN+"','"+MN+"','"+Weight+"','"+Gender+"','"+Nation+"','"+Contact+"','"+Email+"','"+Prof+"','"+Add+"','"+City+"','"+State+"','"+Fee+"')";
               int s=stm.executeUpdate(sql);
               JOptionPane.showMessageDialog(this, s+ " New Record Added Sucessfully!");
               }
               catch(Exception y)
                       {
                           JOptionPane.showMessageDialog(this,y.getMessage());
                       }
               send_mail();
         }
       
        
         
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(this,"Are you sure to go back?");
        if(a==JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
             
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Six.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Six.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Six.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Six.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Six().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
