/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bcet.gym.management.system;
import com.email.durgesh.Email;
import javax.swing.*;
import java.sql.*;



/**
 *
 * @author deves
 */
public class Update extends javax.swing.JFrame {
Connection con;
Statement stm;
ResultSet rs;
 String Email_send;

public void connect()
{
    try
        {
           
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bcet gym project","root","");
           stm=con.createStatement();
        }
        catch(Exception ex)
                {
                  JOptionPane.showMessageDialog(this,ex.getMessage());  
                }
}
public void send_mail() //Function to send a email
    {
        try
        {
          Email email=new Email("codefreaksdevelopers@gmail.com","Codefreaks14581"); 
          //setting the sender adress
          email.setFrom("codefreaksdevelopers@gmail.com","CODEFREAKS");
          //Setting subject
          email.setSubject("BCET Gym");
          //Now setting the Content
          email.setContent("<h1> Your Record has been updated/Modified Sucessfullly.Contact the management if it was not you who initialized it,else ignore.  Thanking you,Codefreaks. </h1>","text/html");
          //Now adding the recievers adress
          email.addRecipient(Email_send);
          //Now sending the email
          
          email.send();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        } 
}
    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
        connect();
        this.setResizable(false);
        this.setSize(1200,800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel17 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Algerian", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Update record");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, -10, 290, 60);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 20, 200, 21);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setText("Age");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 50, 200, 21);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setText("Father's Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 80, 200, 21);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setText("Mothers's Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 110, 200, 21);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setText("Weight(in kgs)");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 140, 200, 21);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 170, 200, 21);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setText("Nationality");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 200, 200, 21);

        jTextField1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(210, 20, 300, 27);

        jTextField2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(210, 50, 300, 27);

        jTextField3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(210, 80, 300, 27);

        jTextField4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(210, 110, 300, 27);

        jTextField5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(210, 140, 300, 27);

        jTextField11.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel1.add(jTextField11);
        jTextField11.setBounds(210, 170, 300, 27);

        jTextField13.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel1.add(jTextField13);
        jTextField13.setBounds(210, 200, 300, 27);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 230, 550, 250);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Other Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setText("Contact Number");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 20, 137, 40);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel10.setText("E-mail");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 60, 54, 40);

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel11.setText("Profession");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 90, 90, 40);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel12.setText("Address");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 130, 69, 40);

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel13.setText("City");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 170, 35, 40);

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel14.setText("State");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 210, 45, 40);

        jTextField7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel2.add(jTextField7);
        jTextField7.setBounds(210, 60, 300, 27);

        jTextField8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel2.add(jTextField8);
        jTextField8.setBounds(210, 140, 300, 27);

        jTextField9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel2.add(jTextField9);
        jTextField9.setBounds(210, 180, 300, 27);

        jTextField6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel2.add(jTextField6);
        jTextField6.setBounds(210, 20, 300, 27);

        jTextField14.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel2.add(jTextField14);
        jTextField14.setBounds(210, 100, 300, 27);

        jTextField15.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jPanel2.add(jTextField15);
        jTextField15.setBounds(210, 220, 300, 27);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(610, 220, 550, 260);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bcet/gym/management/system/images/back.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 10, 80, 80);

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jButton2.setText("UPDATE/MODIFY");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 510, 650, 50);

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabel17.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        jLabel17.setText("Enter Gym Card Number");
        jInternalFrame1.getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 10, 250, 26);

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jTextField12);
        jTextField12.setBounds(250, 10, 120, 30);

        jToggleButton1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jToggleButton1.setText("SEARCH");
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(70, 45, 230, 40);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(430, 70, 390, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(this,"Are you sure to go back?","Confirm!!",JOptionPane.YES_NO_OPTION);
        if(a==JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 int a= JOptionPane.showConfirmDialog(this,"Confirm The Modification of Record with Respective Details!!","Confirm!!",JOptionPane.YES_NO_OPTION);
       if(a==JOptionPane.YES_OPTION)
       {
            String Name=null;
        String FN=null;
        String MN=null;
        String Weight=null;
        String Gender=null;
        String Nation=null;
        String Contact=null;
       String Email;
        String Prof=null;
        String Add=null;
        String City=null;
        String State=null;
        String Fee=null; 
        int GymN,age;
       
         {
              Name= jTextField1.getText();
              age=Integer.parseInt(jTextField2.getText());
              FN=jTextField3.getText();
              MN=jTextField4.getText();
              Weight=jTextField5.getText();
              
              
           Gender=jTextField11.getText();
              
            Nation=jTextField13.getText();
            Contact=jTextField6.getText();
            Email=jTextField7.getText();
            Email_send=Email;
            
           Prof=jTextField14.getText();
            Add=jTextField8.getText();
            City=jTextField9.getText();
            
            State=jTextField15.getText();
        
         
       GymN=Integer.parseInt(jTextField12.getText());
               try
               {
                   
                   String sql="update  gymdaata set Member_Name="+"'"+Name+"'"+" ,Age="+age+" ,Father_Name="+"'"+FN+"'"+" ,Mother_Name="+"'"+MN+"'"+" ,Weight="+"'"+Weight+"'"+" ,Gender="+"'"+Gender+"'"+" ,Nationality="+"'"+Nation+"'"+" ,Contact="+"'"+Contact+"'"+" ,Email="+"'"+Email+"'"+" ,Profression="+"'"+Prof+"'"+" ,Adress="+"'"+Add+"'"+" ,City="+"'"+City+"'"+" ,s_tate="+"'"+State+"'"+" ,Fee="+"'"+Fee+"'"+"where Gym_Card_no="+GymN+" ";
               int s=stm.executeUpdate(sql);
               JOptionPane.showMessageDialog(this, s+ " Record Updated Sucessfully!");
               }
               catch(Exception y)
                       {
                           JOptionPane.showMessageDialog(this,y.getMessage());
                       }
         }
         send_mail();
       }       

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if(jToggleButton1.isSelected())
        {
             jButton2.setEnabled(true);
        int GYM_NO=Integer.parseInt(jTextField12.getText());
         
         try{
             String sql="select * from gymdaata where Gym_Card_no="+GYM_NO+"";
         rs=stm.executeQuery(sql);
         
             while(rs.next()){
         String Name=rs.getString("Member_Name");
         jTextField1.setText(Name);
         
         String Age=rs.getString("Age");
         jTextField2.setText(Age);
         
          String FN=rs.getString("Father_Name");
         jTextField3.setText(FN);
         
           String mN=rs.getString("Mother_Name");
         jTextField4.setText(mN);
         
         String W=rs.getString("Weight");
       jTextField5.setText(mN);
         
          String Gender=rs.getString("Gender");
         jTextField11.setText(Gender);
         
          String N=rs.getString("Nationality");
         jTextField13.setText(N);
         
          String contact=rs.getString("Contact");
         jTextField6.setText(contact);
         
          String mail=rs.getString("Email");
         jTextField7.setText(mail);
         
         String P=rs.getString("Profression");
         jTextField14.setText(P);
         
            String add=rs.getString("Adress");
         jTextField8.setText(add);
         
         
          String city=rs.getString("City");
         jTextField9.setText(city);
         
         
          String State=rs.getString("s_tate");
         jTextField15.setText(State);
         
         
        
         
             }
         
         
       
         }
         catch(Exception z)
         {
             JOptionPane.showMessageDialog(this,z.getMessage());
         }
         
         jToggleButton1.setText("CLEAR");
        }
        else
        {
            jToggleButton1.setText("SEARCH");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
           
            jTextField11.setText("");
            jTextField12.setText("");
            jTextField13.setText("");
            jTextField14.setText("");
            jTextField15.setText("");
            
            jButton2.setEnabled(false);
            
        }
         
         
                 
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
